### ISSUE TITLE
Launcher issue

### ISSUE THREAD

**Issue by Xrot** [lucas-allegri/KnightLauncher#15]
launcher won't save some settings for example when i disable discord RPC it turns back on again by itself after a while

**Comment by lucas-allegri** [comment]
Did this happen after updating to 1.3.2? This update reset all your existing settings from previous versions.

**Comment by Xrot** [comment]
no it just only resets discord RPC back on other settings stay the same

**Comment by lucas-allegri** [comment]
This issue is now **solved** after the following commit
https://github.com/lucas-allegri/KnightLauncher/commit/dc1ee8e9527642f3dcf32fc4fcafa2f5aa42fc39

Changes will be reflected when a **new release** gets published, for now simply make sure to toggle it off every time you start the launcher.

Regards!
