### ISSUE TITLE
Game wont launch using launcher 

### ISSUE THREAD

**Issue by Crotaphos** [lucas-allegri/KnightLauncher#6]
This issue happened as i uninstalled sk and reinstalled a fresh one. I did all the necessary steps such as having the game run on 64 bit java, and pasting the knight launcher contents into sk folder. But as i launch sk with 4gb ram the game wont launch at all . But when i deleted the extra.txt and launch the game directly from steam it works but it wont be as smooth without knight launcher. I hope u can help me with my problem.

**Comment by lucas-allegri** [comment]
Make sure you're actually using a 64-bit Java Virtual Machine (JVM) and not a 32-bit one. That'd most likely be the issue here as you say it doesn't run using 4 GBs of allocated memory, and that's the limitation of 32-bit JVMs.
Additionally I'd suggest to turn off any Garbage Collection (GC) settings from within KnightLauncher settings; such as "Disable G1GC" or "Disable Explicit GC".
Spiral Knights does not need that much amount of RAM allocated to it, 1-2 gigabytes should be already enough, but a 64-bit JVM will make the difference.

Let me know what's the results :)

**Comment by lucas-allegri** [comment]
This does not seem to be an issue with KnightLauncher itself but your Java installation instead, best I can recommend is to make a completely clean installation by removing everything related to it prior to reinstall. Have a nice day.
